name: Project Zero

on: [push, pull_request]


jobs:
  build_and_test:
    name: project0
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
 
      - name: Build Project0 with Maven
        run: mvn -B package --file project-0/pom.xml
        
  publish-jobs:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with: 
          distribution: 'adopt'
          java-version: 11
          check-latest: true
      - run: mvn -B package --file project-0/pom.xml -DskipTests
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
  
  
