name: Project Zero

on: 
  push:
    tags:
       - "v*.*.*"


jobs:
  build_and_test:
    name: project0
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          distribution: 'adopt'
        
      - name: Cache Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build Project0 with Maven
        run: mvn -B package --file project-0/pom.xml
        
  publish-jobs:
    runs-on: macos-latest
    needs: [build_and_test]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with: 
          distribution: 'adopt'
          java-version: 8
          check-latest: true
      - run: mvn -B package --file project-0/pom.xml -DskipTests
      - run: mkdir staging && cp target/*jar-with-dependencies.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
  
  build-docker-image:
    name: Publish to Docker Hub
    runs-on: macos-latest
    needs: [build_and_test]
    
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/project0:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
     
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      
