name: Project Zero

on: [push, pull_request]


jobs:
  build_and_test:
    name: project0
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          distribution: 'adopt'
        
      - name: Cache Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build Project0 with Maven
        run: mvn -B package --file project-0/pom.xml
        
